version: '3'

services:
  app:
    build:
      context: ./node
    image: arturcampos/node:latest
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on: 
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  
  nginx:
    build:
      context: ./nginx
    image: arturcampos/nginx:latest
    container_name: nginx
    networks:
      - node-network
    tty: true
    ports:
      - 8080:8080
    depends_on: 
      - app

networks:
  node-network:
    driver: bridge
  